// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SurveySystem.DAL.Data.Context;

#nullable disable

namespace SurveySystem.DAL.Migrations
{
    [DbContext(typeof(KPISContext))]
    partial class KPISContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SurveySystem.DAL.Data.Models.TbiKPI", b =>
                {
                    b.Property<int>("KPINum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KPINum"));

                    b.Property<int>("DepNo")
                        .HasColumnType("int");

                    b.Property<string>("KPIDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("MeasurementUnit")
                        .HasColumnType("bit");

                    b.Property<int>("TargetedValue")
                        .HasColumnType("int");

                    b.HasKey("KPINum");

                    b.ToTable("Kpis");

                    b.HasData(
                        new
                        {
                            KPINum = 18820007,
                            DepNo = 2,
                            KPIDescription = "Grow sales by 5% per quarter",
                            MeasurementUnit = true,
                            TargetedValue = 100
                        },
                        new
                        {
                            KPINum = 18320088,
                            DepNo = 1,
                            KPIDescription = "Increase Net Promoter Score 25% over the next three years",
                            MeasurementUnit = false,
                            TargetedValue = 80
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
